name: ðŸš€ Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: ðŸ§ª Test
        run: |
          dotnet test

      # TODO mongo password not getting embedded properly some commands fail

      - name: ðŸ“¦ Build
        working-directory: ./USTACLI
        env:
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        run: dotnet pack -c Release

      - name: ðŸš€ Publish to Nuget
        working-directory: ./USTACLI
        env:
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        run: dotnet nuget push ./nupkg/*.nupkg -n -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json

      - name: ðŸš€ Publish to GitHub
        working-directory: ./USTACLI
        env:
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        run: dotnet nuget push ./nupkg/*.nupkg -n -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/lineville/index.json
